<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitae33995b31adb97c22f975e7d64bedc6
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitae33995b31adb97c22f975e7d64bedc6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitae33995b31adb97c22f975e7d64bedc6::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitae33995b31adb97c22f975e7d64bedc6::$classMap;

        }, null, ClassLoader::class);
    }
}
